{
  imports = [
    ./comment_nvim
    ./debugprint
    ./fidget
    ./gitmessenger
    ./gitsigns
    ./leap
    ./lsp
    ./lsp_format
    ./nvim_cmp
    ./nvim_colorizer
    ./nvim_tree
    ./rainbow_delimiters
    ./rust_tools
    ./spider
    ./surround
    ./telescope
    ./treesitter
    ./treesitter_context
    ./trouble
    ./undotree
    ./vim_illuminate
    ./wtf
  ];
}
