{
  imports = [
    ./codeium-nvim
    ./codeium-vim
    ./comment-nvim
    ./debugprint
    ./fidget
    ./gitmessenger
    ./gitsigns
    ./leap
    ./lsp
    ./lsp-format
    ./nvim-cmp
    ./nvim-colorizer
    ./nvim-tree
    ./rainbow-delimiters
    ./rustaceanvim
    ./spider
    ./surround
    ./telescope
    ./todo-comments
    ./treesitter
    ./treesitter-context
    ./trouble
    ./undotree
    ./illuminate
    ./wtf
  ];
}
