{
  imports = [
    ./comment-nvim
    ./fidget
    ./gitmessenger
    ./gitsigns
    ./leap
    ./lsp
    ./lsp-format
    ./nvim-cmp
    ./nvim-colorizer
    ./nvim-tree
    ./rainbow-delimiters
    ./rust-tools
    ./spider
    ./surround
    ./telescope
    ./treesitter
    ./treesitter-context
    ./trouble
    ./undotree
    ./vim-illuminate
  ];
}
