==== Window Management

The following `<LEADER_1>` and `<LEADER_2>` keys may be distinct:

|===
| Keymapping | Behaviour

a| `<LEADER_1>` + `<LEADER_2>` + `SHIFT` + `h`
| Move the active window to the left.

a| `<LEADER_1>` + `<LEADER_2>` + `SHIFT` + `j`
| Move the active window down.

a| `<LEADER_1>` + `<LEADER_2>` + `SHIFT` + `k`
| Move the active window up.

a| `<LEADER_1>` + `<LEADER_2>` + `SHIFT` + `l`
| Move the active window to the right.

a| `<LEADER_1>` + `<LEADER_2>` + `h`
| Decrease the active window's width.

a| `<LEADER_1>` + `<LEADER_2>` + `j`
| Increase the active window's height.

a| `<LEADER_1>` + `<LEADER_2>` + `k`
| Decrease the active window's height.

a| `<LEADER_1>` + `<LEADER_2>` + `l`
| Increase the active window's width.

a| `<LEADER_1>` + `<LEADER_2>` + `n`
| Apply the next layout.

a| `<LEADER_1>` + `<LEADER_2>` + `p`
| Apply the previous layout.

a| `<LEADER_1>` + `SHIFT` + `j`
| Swap the active window with the next one in the stack.

a| `<LEADER_1>` + `SHIFT` + `k`
| Swap the active window with the previous one in the stack.

a| `<LEADER_1>` + `SHIFT` + `q`
| Close the active window.

a| `<LEADER_1>` + `f`
| Toggle the active window's fullscreen state.

a| `<LEADER_1>` + `h`
| Focus the previous workspace in the stack.

a| `<LEADER_1>` + `j`
| Focus the next window in the stack.

a| `<LEADER_1>` + `k`
| Focus the previous window in the stack.

a| `<LEADER_1>` + `l`
| Focus the next workspace in the stack.

a| `<LEADER_1>` + `t`
| Open a new default window.

a| `<LEADER_1>` + `w`
| Toggle the active window's floating state.
|===
