lib:
lib.dotfiles.homeManagerConfiguration.prependPrefix "plugins" [
  ./comment
  ./debugprint
  ./fidget
  ./gitmessenger
  ./gitsigns
  ./illuminate
  ./leap
  ./lsp
  ./lsp-format
  ./nvim-colorizer
  ./nvim-tree
  ./rainbow-delimiters
  ./rustaceanvim
  ./spider
  ./surround
  ./telescope
  ./todo-comments
  ./treesitter
  ./treesitter-context
  ./trouble
  ./undotree
  ./wtf
]
