= dotfiles(1)
:archwiki-dotfiles: link:https://wiki.archlinux.org/title/Dotfiles
:home-configuration-nix-5: link:https://nix-community.github.io/home-manager/options.xhtml
:home-manager: link:https://nix-community.github.io/home-manager
:naho: link:https://github.com/trueNAHO
:os: link:https://github.com/trueNAHO/os
:repository: link:https://github.com/trueNAHO/dotfiles
:version-control-visualization: link:https://github.com/trueNAHO/trueNAHO/blob/master/version_control_visualization/repositories/dotfiles/README.adoc

== Name

dotfiles - NAHO's dotfiles

== Synopsis

*home-manager switch* --flake _flake-uri_

== Description

{naho}[NAHO]'s {archwiki-dotfiles}[dotfiles] managed with {home-manager}[Home
Manager].

== Options

*--flake* _flake-uri[#name]_::

"Build Home Manager configuration from the flake, which must contain the
output `homeConfigurations.name`. If no `name` is specified it will first try
`username@hostname` and then `username`." (home-manager(1))
+
The following derivations are available:
+
* `aarch64-darwin`
* `aarch64-linux`
* `x86_64-darwin`
* `x86_64-linux`

== Examples
:command-base: home-manager switch --flake
:command-local-path: /path/to/repository

:command-local: {command-base} {command-local-path}#
:command-upstream: {command-base} github:trueNAHO/dotfiles#

To install the dotfiles directly from {repository}[upstream], run one of
the following commands:

[,bash,subs="attributes"]
----
{command-upstream}aarch64-darwin
{command-upstream}aarch64-linux
{command-upstream}x86_64-darwin
{command-upstream}x86_64-linux
----

To install the dotfiles from a local copy at `{command-local-path}`, run one of
the following commands:

[,bash,subs="attributes"]
----
{command-local}aarch64-darwin
{command-local}aarch64-linux
{command-local}x86_64-darwin
{command-local}x86_64-linux
----

== See Also

{home-manager}[Home Manager], link:LICENSE[License], {os}[NAHO's NixOS
configurations], {version-control-visualization}[Version Control Visualization],
link:docs/code_of_conduct.adoc[dotfiles.code-of-conduct(7)],
link:docs/contributing.adoc[dotfiles.contributing(7)],
link:docs/design/main.adoc[dotfiles.design(7)],
{home-configuration-nix-5}[home-configuration.nix(5)]
