= dotfiles(1)
:archwiki-dotfiles: link:https://wiki.archlinux.org/title/Dotfiles
:home-configuration-nix-5: link:https://nix-community.github.io/home-manager/options.xhtml
:home-manager: link:https://nix-community.github.io/home-manager
:hosts-each-default-system: link:hosts/eachDefaultSystem.nix
:idprefix:
:idseparator: -
:naho: link:https://github.com/trueNAHO
:os: link:https://github.com/trueNAHO/os
:repository-path: trueNAHO/dotfiles
:repository-star-history-align: center
:repository-star-history-alt: Star History Chart
:repository-star-history-width: 100%
:toc:
:version-control-visualization: link:https://github.com/trueNAHO/trueNAHO/blob/master/version_control_visualization/repositories/dotfiles/README.adoc

:repository-flake-url: github:{repository-path}
:repository-star-history-src-dark: https://api.star-history.com/svg?repos={repository-path}&type=Date&theme=dark
:repository-star-history-src-light: https://api.star-history.com/svg?repos={repository-path}&type=Date
:repository: link:https://github.com/{repository-path}

== Name

dotfiles - NAHO's dotfiles

== Synopsis

*home-manager switch* --flake _flake-uri_

== Description

{naho}[NAHO]'s {archwiki-dotfiles}[dotfiles] managed with {home-manager}[Home
Manager].

== Options

*--flake* _flake-uri[#name]_::

[,home-manager(1)]
____
Build Home Manager configuration from the flake, which must contain the output
`homeConfigurations.name`. If no `name` is specified it will first try
`username@hostname` and then `username`.
____

== Packages

=== aarch64-darwin

{hosts-each-default-system}[Uses all internal `aarch64-darwin` architecture
modules.]

=== aarch64-linux

{hosts-each-default-system}[Uses all internal `aarch64-linux` architecture
modules.]

=== x86_64-darwin

{hosts-each-default-system}[Uses all internal `x86_64-darwin` architecture
modules.]

=== x86_64-linux

{hosts-each-default-system}[Uses all internal `x86_64-linux` architecture
modules.]

== Examples
:command-base: home-manager switch --flake
:command-local-path: /path/to/repository

:command-local: {command-base} {command-local-path}#
:command-upstream: {command-base} {repository-flake-url}#

To build the <<packages, packages>> directly from {repository}[upstream] using
{home-manager}[`home-manager`], run one of the following commands:

[,bash,subs="attributes"]
----
{command-upstream}aarch64-darwin
{command-upstream}aarch64-linux
{command-upstream}x86_64-darwin
{command-upstream}x86_64-linux
----

To build the <<packages, packages>> from a local copy at `{command-local-path}`
using {home-manager}[`home-manager`], run one of the following commands:

[,bash,subs="attributes"]
----
{command-local}aarch64-darwin
{command-local}aarch64-linux
{command-local}x86_64-darwin
{command-local}x86_64-linux
----

== See Also

{repository-star-history-src-dark}[GitHub Star History], {home-manager}[Home
Manager], link:LICENSE[License], {os}[NAHO's NixOS configurations],
{version-control-visualization}[Version Control Visualization],
link:docs/code_of_conduct.adoc[dotfiles.code-of-conduct(7)],
link:docs/contributing.adoc[dotfiles.contributing(7)],
link:docs/design/main.adoc[dotfiles.design(7)],
{home-configuration-nix-5}[home-configuration.nix(5)]

ifdef::env-github[]
[subs=attributes]
++++
<p align="{repository-star-history-align}">
  <picture>
    <source
      media="(prefers-color-scheme: dark)"
      srcset="{repository-star-history-src-dark}"
    />

    <source
      media="(prefers-color-scheme: light)"
      srcset="{repository-star-history-src-light}"
    />

    <img
      alt="{repository-star-history-alt}"
      src="{repository-star-history-src-dark}"
      width="{repository-star-history-width}"
    />
  </picture>
</p>
++++
endif::[]
