= dotfiles(1)
:archwiki-dotfiles: link:https://wiki.archlinux.org/title/Dotfiles
:home-configurations-each-default-system: link:home_configurations/eachDefaultSystem/default.nix
:home-configuration-nix-5: link:https://nix-community.github.io/home-manager/options.xhtml
:home-manager: link:https://nix-community.github.io/home-manager
:idprefix:
:idseparator: -
:naho: link:https://github.com/trueNAHO
:os: link:https://github.com/trueNAHO/os
:repository-path: trueNAHO/dotfiles
:repository-star-history-align: center
:repository-star-history-alt: Star History Chart
:repository-star-history-width: 100%
:toc:
:version-control-visualization: link:https://github.com/trueNAHO/trueNAHO/blob/master/version_control_visualization/repositories/dotfiles/README.adoc

:repository-flake-url: github:{repository-path}
:repository-star-history-src-dark: https://api.star-history.com/svg?repos={repository-path}&type=Date&theme=dark
:repository-star-history-src-light: https://api.star-history.com/svg?repos={repository-path}&type=Date
:repository-raw: https://github.com/{repository-path}

:repository: link:{repository-raw}
:repository-raw-stargazers: {repository-raw}/stargazers

== Name

dotfiles - NAHO's dotfiles

== Synopsis

*home-manager switch* --flake _flake-uri_

== Description

{naho}[NAHO]'s {archwiki-dotfiles}[dotfiles] managed with {home-manager}[Home
Manager].

== Options

*--flake* _flake-uri[#name]_::

[,home-manager(1)]
____
Build Home Manager configuration from the flake, which must contain the output
`homeConfigurations.name`. If no `name` is specified it will first try
`username@hostname` and then `username`.
____

== Packages

|===
| Packages | Description

a|
- {home-configurations-each-default-system}[`aarch64-darwin-eachDefaultSystem`]
- {home-configurations-each-default-system}[`aarch64-linux-eachDefaultSystem`]
- {home-configurations-each-default-system}[`x86_64-darwin-eachDefaultSystem`]
- {home-configurations-each-default-system}[`x86_64-linux-eachDefaultSystem`]
a| Uses all `modules`.
|===

== Examples
:command-base: home-manager switch --flake
:command-local-path: /path/to/repository

:command-local: {command-base} {command-local-path}#
:command-upstream: {command-base} {repository-flake-url}#

To build the <<packages, packages>> directly from {repository}[upstream] using
{home-manager}[`home-manager`], run one of the following commands:

[,bash,subs="attributes"]
----
{command-upstream}aarch64-darwin-eachDefaultSystem
{command-upstream}aarch64-linux-eachDefaultSystem
{command-upstream}x86_64-darwin-eachDefaultSystem
{command-upstream}x86_64-linux-eachDefaultSystem
----

To build the <<packages, packages>> from a local copy at `{command-local-path}`
using {home-manager}[`home-manager`], run one of the following commands:

[,bash,subs="attributes"]
----
{command-local}aarch64-darwin-eachDefaultSystem
{command-local}aarch64-linux-eachDefaultSystem
{command-local}x86_64-darwin-eachDefaultSystem
{command-local}x86_64-linux-eachDefaultSystem
----

== See Also

{repository-star-history-src-dark}[GitHub Star History], {home-manager}[Home
Manager], link:LICENSE[License], {os}[NAHO's NixOS configurations],
{version-control-visualization}[Version Control Visualization],
link:docs/code_of_conduct.adoc[dotfiles.code-of-conduct(7)],
link:docs/contributing.adoc[dotfiles.contributing(7)],
link:docs/design/main.adoc[dotfiles.design(7)],
{home-configuration-nix-5}[home-configuration.nix(5)]

ifdef::env-github[]
[subs=attributes]
++++
<a href="{repository-raw-stargazers}">
  <p align="{repository-star-history-align}">
    <picture>
      <source
        media="(prefers-color-scheme: dark)"
        srcset="{repository-star-history-src-dark}"
      />

      <source
        media="(prefers-color-scheme: light)"
        srcset="{repository-star-history-src-light}"
      />

      <img
        alt="{repository-star-history-alt}"
        src="{repository-star-history-src-dark}"
        width="{repository-star-history-width}"
      />
    </picture>
  </p>
</a>
++++
endif::[]
