# This module is expected to contain all internal module options.
{
  imports = [
    ../../../modules/agenix/homeManagerModules/default
    ../../../modules/homeManager/fonts
    ../../../modules/homeManager/home/packages/acpi
    ../../../modules/homeManager/home/packages/aria
    ../../../modules/homeManager/home/packages/asciidoctor
    ../../../modules/homeManager/home/packages/bandwhich
    ../../../modules/homeManager/home/packages/catimg
    ../../../modules/homeManager/home/packages/catnip
    ../../../modules/homeManager/home/packages/diskonaut
    ../../../modules/homeManager/home/packages/du-dust
    ../../../modules/homeManager/home/packages/dua
    ../../../modules/homeManager/home/packages/duf
    ../../../modules/homeManager/home/packages/fd
    ../../../modules/homeManager/home/packages/ffmpeg
    ../../../modules/homeManager/home/packages/file
    ../../../modules/homeManager/home/packages/gcc
    ../../../modules/homeManager/home/packages/gimp
    ../../../modules/homeManager/home/packages/glava
    ../../../modules/homeManager/home/packages/glow
    ../../../modules/homeManager/home/packages/gping
    ../../../modules/homeManager/home/packages/gpt4all
    ../../../modules/homeManager/home/packages/inkscape
    ../../../modules/homeManager/home/packages/kdenlive
    ../../../modules/homeManager/home/packages/killall
    ../../../modules/homeManager/home/packages/libreoffice
    ../../../modules/homeManager/home/packages/neofetch
    ../../../modules/homeManager/home/packages/p7zip
    ../../../modules/homeManager/home/packages/parallel
    ../../../modules/homeManager/home/packages/pipe-rename
    ../../../modules/homeManager/home/packages/poppler_utils
    ../../../modules/homeManager/home/packages/procs
    ../../../modules/homeManager/home/packages/pstree
    ../../../modules/homeManager/home/packages/ripgrep-all
    ../../../modules/homeManager/home/packages/rustup
    ../../../modules/homeManager/home/packages/thunderbird
    ../../../modules/homeManager/home/packages/tldr
    ../../../modules/homeManager/home/packages/tokei
    ../../../modules/homeManager/home/packages/tree
    ../../../modules/homeManager/home/packages/unzip
    ../../../modules/homeManager/home/packages/wl-clipboard
    ../../../modules/homeManager/home/packages/xdg-utils
    ../../../modules/homeManager/home/packages/zip
    ../../../modules/homeManager/home/sessionVariables
    ../../../modules/homeManager/home/shellAliases
    ../../../modules/homeManager/nixpkgs/config/allowUnfree
    ../../../modules/homeManager/programs/bash
    ../../../modules/homeManager/programs/bashmount
    ../../../modules/homeManager/programs/bat
    ../../../modules/homeManager/programs/borgmatic
    ../../../modules/homeManager/programs/btop
    ../../../modules/homeManager/programs/direnv
    ../../../modules/homeManager/programs/eza
    ../../../modules/homeManager/programs/feh
    ../../../modules/homeManager/programs/firefox
    ../../../modules/homeManager/programs/fish
    ../../../modules/homeManager/programs/fzf
    ../../../modules/homeManager/programs/gh
    ../../../modules/homeManager/programs/git
    ../../../modules/homeManager/programs/gpg
    ../../../modules/homeManager/programs/home-manager
    ../../../modules/homeManager/programs/imv
    ../../../modules/homeManager/programs/jq
    ../../../modules/homeManager/programs/kitty
    ../../../modules/homeManager/programs/lazygit
    ../../../modules/homeManager/programs/man
    ../../../modules/homeManager/programs/mpv
    ../../../modules/homeManager/programs/password-store
    ../../../modules/homeManager/programs/qutebrowser
    ../../../modules/homeManager/programs/ripgrep
    ../../../modules/homeManager/programs/rofi
    ../../../modules/homeManager/programs/swaylock
    ../../../modules/homeManager/programs/taskwarrior
    ../../../modules/homeManager/programs/wlogout
    ../../../modules/homeManager/programs/xplr
    ../../../modules/homeManager/programs/zathura
    ../../../modules/homeManager/programs/zellij
    ../../../modules/homeManager/programs/zoxide
    ../../../modules/homeManager/services/borgmatic
    ../../../modules/homeManager/services/dunst
    ../../../modules/homeManager/services/easyeffects
    ../../../modules/homeManager/services/gammastep
    ../../../modules/homeManager/services/gpg-agent
    ../../../modules/homeManager/services/swayidle
    ../../../modules/homeManager/systemd/user/tmpfiles/rules
    ../../../modules/homeManager/wayland/windowManager/hyprland
    ../../../modules/homeManager/xdg
    ../../../modules/nix-alien
    ../../../modules/programs/nixvim
    ../../../modules/services/battery
    ../../../modules/stylix
    ../../../modules/wayland
  ];
}
