#!/usr/bin/env bash

# `xinitrc` configures the initialisation of xinit.

declare -r system_modmap="/etc/X11/xinit/.Xmodmap"
declare -r system_programs="/etc/X11/xinit/xinitrc.d"
declare -r system_resources="/etc/X11/xinit/.Xresources"
declare -r user_modmap="$HOME/.Xmodmap"
declare -r user_resources="$HOME/.Xresources"

# Load entire closure in background to yield control back to the runtime as
# soon as possible. Make sure no processes lock the closure. Otherwise no
# further statements will be executed. For consistency load every process in
# the background.
_async_load() { {
  # Start X11 compositor.
  picom &

  # Set color temperature of display according to time of day.
  redshift &
} & }

# Replace current shell with a graphical user interface.
_exec_graphical_user_interface() {
  exec awesome
}

# Set configurations for various tools.
_set_configs() {
  [[ -f "$system_resources" ]]  && xrdb -merge "$system_resources"
  [[ -f "$system_modmap" ]]     && xmodmap "$system_modmap"

  [[ -f "$user_resources" ]] && xrdb -merge "$user_resources"
  [[ -f "$user_modmap" ]]    && xmodmap "$user_modmap"

}

# Source bash scripts located in `system_programs`.
_source_system_programs() {
  declare file
  if [[ -d "$system_programs" ]]; then
   for file in "$system_programs"/?*.sh; do
    [[ -x "$file" ]] && source "$file"
   done
  fi
}

# Asynchronous function should be called after synchronous one to assure
# correct processing order. Make sure the `exec` command is the last one
# executed in this script. No further statements will be executed.
_main() {
  _set_configs
  _source_system_programs
  _async_load
  _exec_graphical_user_interface
}

_main
