#!/usr/bin/env bash

source config/eww-config

readonly DEFAULT_ICON="󰂑"

# https://github.com/elkowar/eww/discussions/300
battery_average="$(
    upower -i $(upower -e | grep BAT) |
        awk '/percentage:/ {sub(/%$/, "", $NF); print $NF; exit}'
)"

# https://askubuntu.com/questions/69556
if ! battery_state="$(
    upower -i $(upower -e | grep BAT) | awk '/state:/ {print $NF; exit}'
)"; then
    printf '%s\n' "$DEFAULT_ICON"
    exit 0
fi

icon=""

if [[ "$battery_state" == "discharging" ]]; then
    if ((battery_average < 0)); then
        icon="$DEFAULT_ICON"
    elif ((battery_average < 10)); then
        icon="󰂎"
    elif ((battery_average < 20)); then
        icon="󰁺"
    elif ((battery_average < 30)); then
        icon="󰁻"
    elif ((battery_average < 40)); then
        icon="󰁼"
    elif ((battery_average < 50)); then
        icon="󰁽"
    elif ((battery_average < 60)); then
        icon="󰁾"
    elif ((battery_average < 70)); then
        icon="󰁿"
    elif ((battery_average < 80)); then
        icon="󰂀"
    elif ((battery_average < 90)); then
        icon="󰂁"
    elif ((battery_average < 100)); then
        icon="󰂂"
    elif ((battery_average == 100)); then
        icon="󰁹"
    else
        icon="$DEFAULT_ICON"
    fi
else
    if ((battery_average < 0)); then
        icon="$DEFAULT_ICON"
    elif ((battery_average < 10)); then
        icon="󰢟"
    elif ((battery_average < 20)); then
        icon="󰢜"
    elif ((battery_average < 30)); then
        icon="󰂆"
    elif ((battery_average < 40)); then
        icon="󰂇"
    elif ((battery_average < 50)); then
        icon="󰂈"
    elif ((battery_average < 60)); then
        icon="󰢝"
    elif ((battery_average < 70)); then
        icon="󰂉"
    elif ((battery_average < 80)); then
        icon="󰢞"
    elif ((battery_average < 90)); then
        icon="󰂊"
    elif ((battery_average < 100)); then
        icon="󰂋"
    elif ((battery_average == 100)); then
        icon="󰂅"
    else
        icon="$DEFAULT_ICON"
    fi
fi

printf '%s\n' "$icon"
