#!/usr/bin/env bash

help_message() {
  printf '%b\n' \
    "Usage: $0 [input_files] [output_file]" \
    "\tinput_files\tall files used for compiling output file" \
    "\toutput_file\tname given to compiled file" \
    >&2
  exit 1
}

# At least two arguments must be given
(( $# < 2 )) && help_message

declare -ar input_files=( "${@:1:${#@}-1}" )
declare -r output_file=${*: -1}

# Optional flag: -std=c++17
if g++ \
  -Wall \
  -Weffc++ \
  -Werror \
  -Wextra \
  -Wsign-conversion \
  -o "$output_file" \
  -pedantic-errors \
  "${input_files[@]}";
then
  "./$output_file"
fi

# vim: ft=bash fdm=marker et sts=2 sw=2 ts=2 tw=80
