#!/usr/bin/env bash

download_archive="downloaded.log"
source="source.url"

xargs youtube-dl \
  --audio-format "aac" \
  --download-archive "$download_archive" \
  --extract-audio \
  --no-overwrites \
  --output '%(autonumber)s_%(title)s.%(ext)s' \
  --restrict-filenames \
  --yes-playlist \
  -i \
  < <(cat "$source")

printf "==> Number of files (excluding %s): %d\n" \
  "$download_archive and $source" \
  "$(wc -l < <(ls -I "$download_archive" -I "$source"))"
