#!/usr/bin/env bash
# shellcheck disable=all

{{ template "lib/utilities/is_command_available" }}
{{ template "lib/utilities/status" }}
{{ template "lib/utilities/status_error" }}

# @url https://github.com/Jguer/yay
# Install yay.
install_yay() {
  declare -r -a yay_build_dependencies=( base-devel git )

  # Resolve build dependencies.
  status "resolve build dependencies for yay"
  pacman_dependencies "${yay_build_dependencies[@]}"
  for dependency in "${yay_build_dependencies[@]}"; do
    if ! is_command_available "$dependency"; then
      status_error "failed to install build dependency for yay: $dependency"
      return 1
    fi
  done

  # Install yay inside a temporary directory.
  declare -r current_dir="$PWD"
  declare -r tmp_dir="$(mktemp -d)"
  cd "$tmp_dir" \
      && git clone https://aur.archlinux.org/yay.git \
      && cd yay \
      && makepkg -si \
      && cd "$current_dir" \
      && rm -fr "$tmp_dir"
}
