#!/usr/bin/env bash
# shellcheck disable=all

{{ template "lib/utilities/status" }}

# @url https://www.chezmoi.io/user-guide/templating/#using-chezmoitemplates-for-creating-similar-files
# Print details about unsupported operating system. Operating system must be
# passed as template argument.
status_unsupported_os() {
  status "unsupported operating system: {{ . }}"
}
