#!/usr/bin/env bash
# shellcheck disable=all

{{ template "lib/utilities/status" }}

# Prompt yes or no and return true for valid entries and false for all other
# entries. Valid entries are "yes", "y", or "" (an empty answer) and are checked
# case insensitive. All arguments are used to construct the prompt.
yes_or_no() {
  read -er -p "$(status)$* [y/n]: " reply
  case "${reply,,}" in
    "" | y | yes) return 0 ;;
    *) return 1 ;;
  esac
}
