#!/usr/bin/env bash

readonly LEFTWM_TMP_THEME_DOWN_FILE="/tmp/leftwm-theme-down"

load_theme() {
    leftwm_theme_file="$SCRIPTPATH/theme.ron"
    leftwm-command "LoadTheme $leftwm_theme_file"
}

start_status_bars() {
    eww_config_dir="$SCRIPTPATH/eww"

    leftwm_state_workspaces="$(leftwm-state --quit | jq '.workspaces')"

    while read -r file; do
        esh \
            -o "${file%.esh}" \
            "$file" \
            "leftwm_state_workspaces=${leftwm_state_workspaces}" \
            &
    done < <(find "$eww_config_dir" -type f -name "*.esh")

    wait

    eww daemon --config "$eww_config_dir"

    workspace_count="$(jq length <<<"$leftwm_state_workspaces")"

    for ((i = 0; i < workspace_count; i++)); do
        eww open --config "$eww_config_dir" "workspace-${i}-bar" &
    done

    wait
}

unload_theme() {
    leftwm_theme_down_file="$SCRIPTPATH/down"

    if [[ -f "$LEFTWM_TMP_THEME_DOWN_FILE" ]]; then
        if [[ -x "$LEFTWM_TMP_THEME_DOWN_FILE" ]]; then
            "$LEFTWM_TMP_THEME_DOWN_FILE"
        fi

        rm "$LEFTWM_TMP_THEME_DOWN_FILE"
    fi

    ln --symbolic "$leftwm_theme_down_file" "$LEFTWM_TMP_THEME_DOWN_FILE"
}

main() {
    if [[ -z "$LD_LIBRARY_PATH" ]]; then
        LD_LIBRARY_PATH=":/usr/local/lib"
    fi

    export LD_LIBRARY_PATH

    # http://mywiki.wooledge.org/BashFAQ/028
    # https://stackoverflow.com/questions/59895
    SCRIPTPATH="$(
        cd -- "$(dirname -- "${BASH_SOURCE[0]}")" &>/dev/null && pwd -P
    )"

    export SCRIPTPATH

    unload_theme

    start_status_bars &
    load_theme &

    wait
}

main "$@"
