-- history. How many command lines are remembered.
--      set hi=10000
-- wildchar. Key that triggers command-line expansion.
--      set wc=9
-- wildcharm. Like 'wildchar' but can also be used in a mapping.
--      set wcm=0
-- wildmode. Specifies how command line completion works.
--      set wim=full
-- suffixes. List of file name extensions that have a lower priority.
--      set su=.bak,~,.o,.h,.info,.swp,.obj
-- suffixesadd. List of file name extensions added when searching for a file.
-- (local to buffer)
--      set sua=
-- wildignore. List of patterns to ignore files for file name completion.
--      set wig=
-- fileignorecase. Ignore case when using file names.
--      set nofic    fic
-- wildignorecase. Ignore case when completing file names.
--      set nowic    wic
-- wildmenu. Command-line completion shows a list of matches.
--      set wmnu    nowmnu
-- cedit. Key used to open the command-line window.
--      set cedit=
-- cmdwinheight. Height of the command-line window.
--      set cwh=7
