-- diff	use diff mode for the current window
-- 	(local to window)
--  	set nodiff	diff
-- diffopt	options for using diff mode
--  	set dip=internal,filler,closeoff
-- diffexpr	expression used to obtain a diff file
--  	set dex=
-- patchexpr	expression used to patch a file
--  	set pex=
