-- showtabline. 0, 1 or 2; when to use a tab pages line.
--  	set stal=1
-- tabpagemax. Maximum number of tab pages to open for -p and "tab all".
--  	set tpm=50
-- tabline. Custom tab pages line.
--  	set tal=
