-- selection. "old", "inclusive" or "exclusive"; how selecting text behaves.
--      set sel=inclusive
-- selectmode. "mouse", "key" and/or "cmd"; when to start Select mode.
--     instead of Visual mode
--      set slm=
-- clipboard. "unnamed" to use the * register like unnamed register.
--     "autoselect" to always put selected text on the clipboard
--      set cb=
-- keymodel. "startsel" and/or "stopsel"; what special keys can do.
--      set km=
