-- tagbsearch. Use binary searching in tags files.
--  	set tbs	notbs
-- taglength. Number of significant characters in a tag name or zero.
--  	set tl=0
-- tags. List of file names to search for tags. (global or local to buffer)
--  	set tag=./tags;,tags
-- tagcase. How to handle case when searching in tags files:. "followic" to
-- follow 'ignorecase', "ignore" or "match" (global or local to buffer)
--  	set tc=followic
-- tagrelative. File names in a tags file are relative to the tags file.
--  	set tr	notr
-- tagstack. A :tag command will use the tagstack.
--  	set tgst	notgst
-- showfulltag. When completing tags in Insert mode show more info.
--  	set nosft	sft
-- tagfunc. A function to be used to perform tag searches. (local to buffer)
--  	set tfu=
-- cscopeprg. Command for executing cscope.
--  	set csprg=cscope
-- cscopetag. Use cscope for tag commands.
--  	set nocst	cst
-- cscopetagorder. 0 or 1; the order in which ":cstag" performs a search.
--  	set csto=0
-- cscopeverbose. Give messages when adding a cscope database.
--  	set csverb	nocsverb
-- cscopepathcomp. How many components of the path to show.
--  	set cspc=0
-- cscopequickfix. When to open a quickfix window for cscope.
--  	set csqf=
-- cscoperelative. File names in a cscope file are relative to that file.
--  	set nocsre	csre
