-- scrolljump	minimal number of lines to scroll at a time
--  	set sj=1
-- title	show info in the window title
--  	set notitle	title
-- titlelen	percentage of 'columns' used for the window title
--  	set titlelen=85
-- titlestring	when not empty, string to be used for the window title
--  	set titlestring=
-- titleold	string to restore the title to when exiting Vim
--  	set titleold=
-- icon	set the text of the icon for this window
--  	set noicon	icon
-- iconstring	when not empty, text for the icon of this window
--  	set iconstring=
