-- scrolljump. Minimal number of lines to scroll at a time.
--  	set sj=1
-- title. Show info in the window title.
--  	set notitle	title
-- titlelen. Percentage of 'columns' used for the window title.
--  	set titlelen=85
-- titlestring. When not empty, string to be used for the window title.
--  	set titlestring=
-- titleold. String to restore the title to when exiting Vim.
--  	set titleold=
-- icon. Set the text of the icon for this window.
--  	set noicon	icon
-- iconstring. When not empty, text for the icon of this window.
--  	set iconstring=
