-- mouse	list of flags for using the mouse
--  	set mouse=
-- mousemodel	"extend", "popup" or "popup_setpos"; what the right
-- 	mouse button is used for
--  	set mousem=extend
-- mousetime	maximum time in msec to recognize a double-click
--  	set mouset=500
