-- 25 various

-- virtualedit	when to use virtual editing: "block", "insert", "all"
-- 	and/or "onemore"
--  	set ve=
-- eventignore	list of autocommand events which are to be ignored
--  	set ei=
-- loadplugins	load plugin scripts when starting up
--  	set lpl	nolpl
-- exrc	enable reading .vimrc/.exrc/.gvimrc in the current directory
--  	set noex	ex
-- secure	safer working with script files in the current directory
--  	set nosecure	secure
-- gdefault	use the 'g' flag for ":substitute"
--  	set nogd	gd
-- maxfuncdepth	maximum depth of function calls
--  	set mfd=100
-- sessionoptions	list of words that specifies what to put in a session file
--  	set ssop=blank,buffers,curdir,folds,help,tabpages,winsize
-- viewoptions	list of words that specifies what to save for :mkview
--  	set vop=folds,cursor,curdir
-- viewdir	directory where to store files with :mkview
--  	set vdir=/home/noah/.local/share/nvim/view//
-- viminfo	list that specifies what to write in the ShaDa file
--  	set vi=!,'100,<50,s10,h
-- bufhidden	what happens with a buffer when it's no longer in a window
-- 	(local to buffer)
--  	set bh=
-- buftype	empty, "nofile", "nowrite", "quickfix", etc.: type of buffer
-- 	(local to buffer)
--  	set bt=
-- buflisted	whether the buffer shows up in the buffer list
-- 	(local to buffer)
--  	set bl	nobl
-- debug	set to "msg" to see all error messages
--  	set debug=
-- signcolumn	whether to show the signcolumn
-- 	(local to window)
--  	set scl=auto
-- pyxversion	whether to use Python 2 or 3
--  	set pyx=0
