#!/usr/bin/env bash

source config/eww-config

# https://wiki.archlinux.org/title/Backlight
readonly ACPI_BACKLIGHT_DIR="/sys/class/backlight"
readonly DEFAULT_ICON="󰃠"

eww_update_brightness_icon() {
    icon=""

    if (($1 < 0)); then
        icon="$DEFAULT_ICON"
    elif (($1 == 0)); then
        icon="󰃚"
    elif (($1 < 20)); then
        icon="󰃛"
    elif (($1 < 40)); then
        icon="󰃜"
    elif (($1 < 60)); then
        icon="󰃝"
    elif (($1 < 80)); then
        icon="󰃞"
    elif (($1 < 100)); then
        icon="󰃟"
    elif (($1 == 100)); then
        icon="󰃠"
    else
        icon="$DEFAULT_ICON"
    fi

    # https://github.com/elkowar/eww/discussions/300
    eww --config "$EWW_CONFIG" update "brightness-icon=${icon}"
}

get_brightness() {
    printf '%d\n' "$(($(brightnessctl get) * 100 / $(brightnessctl max)))"
}

update() {
    brightness="$(get_brightness)"
    eww_update_brightness_icon "$brightness"
    printf '%d\n' "$brightness"
}

main() {
    update_interval="$1"

    brightness_dir="$(
        find "$ACPI_BACKLIGHT_DIR" -mindepth 1 -maxdepth 1 | head --lines 1
    )"

    brightness_file="${brightness_dir}/brightness"

    if [[ -f "$brightness_file" ]]; then
        update

        inotifywait --quiet -m -e modify "$brightness_file" |
            while read -r _; do update; done
    else
        while get_brightness && sleep "$update_interval"; do :; done
    fi
}

main "$@"
