---
name: Docs

on:
  push:
    branches:
      - master

permissions:
  contents: read
  id-token: write
  pages: write

concurrency:
  cancel-in-progress: true
  group: pages

jobs:
  docs:
    runs-on: ubuntu-22.04

    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}

    steps:
      - uses: actions/checkout@v4
      - uses: DeterminateSystems/nix-installer-action@v10
      - uses: DeterminateSystems/magic-nix-cache-action@v4
      - run: nix build .#docs

      - uses: actions/upload-pages-artifact@v3
        with:
          path: result/usr/share/doc

      - uses: actions/deploy-pages@v4
